version: '3.8'
services:
  api:
    build:
      context: /api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "587:587"
    volumes:
      - "./api/data/instance:/app/instance"
    restart: unless-stopped

  chat:
    build:
      context: /chat
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    depends_on:
      - api